In [4]:
import platform
platform.platform

In [15]:
LOCAL_DATA = "../../data/aita_top_subs.csv"
COLAB_DATA = "https://raw.githubusercontent.com/macss-berkeley/compss-211a/main/data/aita_top_subs.csv"

COLUMNS = [
    "idstr",
    "created",
    "title",
    "selftext",
    "score",
    "num_comments",
    "flair_text",
]

In [18]:
#how to import data file from these strings
data_path = COLAB_DATA
df = pd.read_csv(data_path, usecols=COLUMNS) #only imports the one you have specified

In [19]:
# Local Python kernel
df

,idstr,created,title,selftext,score,num_comments,flair_text
0,t3_9mw228,1539142774,AITA for calling 911 on a friend for drunk dri...,I’ve officially been booted from my social cir...,12418.0,2082.0,not the a-hole
1,t3_9oczd2,1539612476,AITA for having sex with my fiancé?,So I live on a second floor of an apartment co...,9354.0,1014.0,Not the A-hole
2,t3_9p7m8t,1539854244,AITA For yelling at my housemates girlfriend b...,"After a big night out my housemate, his girlfr...",3854.0,653.0,Not the A-hole
3,t3_9q9kea,1540175338,AITA for getting annoyed at a couple for bring...,"This couple decided to bring their son, I assu...",14210.0,522.0,Not the A-hole
4,t3_9qo0jb,1540293729,AITA For telling her to fuck off?,"I was dating this girl for almost two years, a...",5837.0,559.0,Not the A-hole
...,...,...,...,...,...,...,...
4995,t3_rh4h3r,1639589594,AITA for refusing to paint a new mural in our ...,"When we first got married, I spent months pain...",6701.0,816.0,Not the A-hole
4996,t3_rh7b72,1639596878,AITA for having the girl my brother got pregna...,I 23f have a brother 18m who I love with all m...,7742.0,767.0,Not the A-hole
4997,t3_rhkiqm,1639635795,AITA for not wanting to make my friend a weddi...,So I have a Degree in Fashion which some peopl...,6664.0,1113.0,NaN
4998,t3_rhlg1n,1639639388,AITA for giving my husband the silent treatment?,I (30F) and my husband (30M) recently moved in...,4427.0,740.0,NaN
4999,t3_rhp3w9,1639655198,AITA for suggesting to my fiancée that we make...,I'm getting married in 7 months and one week a...,5366.0,1761.0,NaN

In [ ]:
# Colab kernel
data_path = COLAB_DATA

In [20]:
df.head()

,idstr,created,title,selftext,score,num_comments,flair_text
0,t3_9mw228,1539142774,AITA for calling 911 on a friend for drunk dri...,I’ve officially been booted from my social cir...,12418.0,2082.0,not the a-hole
1,t3_9oczd2,1539612476,AITA for having sex with my fiancé?,So I live on a second floor of an apartment co...,9354.0,1014.0,Not the A-hole
2,t3_9p7m8t,1539854244,AITA For yelling at my housemates girlfriend b...,"After a big night out my housemate, his girlfr...",3854.0,653.0,Not the A-hole
3,t3_9q9kea,1540175338,AITA for getting annoyed at a couple for bring...,"This couple decided to bring their son, I assu...",14210.0,522.0,Not the A-hole
4,t3_9qo0jb,1540293729,AITA For telling her to fuck off?,"I was dating this girl for almost two years, a...",5837.0,559.0,Not the A-hole

In [21]:
df.shape

(5000, 7)

In [22]:
df.dtypes

idstr            object
created           int64
title            object
selftext         object
score           float64
num_comments    float64
flair_text       object
dtype: object

In [23]:
df.columns

Index(['idstr', 'created', 'title', 'selftext', 'score', 'num_comments',
       'flair_text'],
      dtype='object')

In [24]:
df.dropna(subset="selftext", inplace=True)

In [28]:
df.groupby("flair_text").size().sort_values(ascending=False)

flair_text
Not the A-hole         3585
Asshole                 446
Everyone Sucks          116
No A-holes here         105
UPDATE                   98
Not enough info          28
META                      6
Update                    6
Fake Story                1
I crave validation!       1
Judgment denied.          1
META Asshole              1
Probably Fake             1
Quality Shitpost          1
not the a-hole            1
probably fake             1
quality shitpost          1
weeabo h8r                1
dtype: int64